[419] plantage autocomplete si label vide
mission-apprentissage/labonnealternance-old pull request #161
Opened 2021-02-18 10:36 UTC by alanlr

2021-02-18 13:03 UTC, bdavidxyz requested changes

2021-02-18 13:03 UTC, bdavidxyz commented on ui/components/AutoCompleteField/AutoCompleteField.js
> +import highlightItem from "../../services/hightlightItem";
est-ce que à l'avenir on pourrait essayer un import absolu uniquement ?

2021-02-18 13:03 UTC, bdavidxyz commented on ui/components/AutoCompleteField/AutoCompleteField.js
> +  return item ? item.label : "";
renvoie undefined si label est undefined, et un autre type que String si item.label n'est pas une String. 
Solution proposée : item?.label?.toString() ?? ""
Source : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Op%C3%A9rateurs/Nullish_coalescing_operator

2021-02-18 13:03 UTC, bdavidxyz commented on ui/components/SearchForTrainingsAndJobs/components/SearchForm.js
> +} from "components/AutoCompleteField/AutoCompleteField";
👍 top pour l'import absolu

2021-02-19 08:39 UTC, alanlr commented on ui/components/AutoCompleteField/AutoCompleteField.js
> +import highlightItem from "../../services/hightlightItem";
done

2021-02-19 08:39 UTC, alanlr commented on ui/components/AutoCompleteField/AutoCompleteField.js
> +  return item ? item.label : "";
done

2021-02-19 09:15 UTC, merged