Gestion des offres Matcha
mission-apprentissage/labonnealternance-old pull request #211
Opened 2021-04-02 10:35 UTC by alanlr

2021-04-02 12:11 UTC, bdavidxyz requested changes

2021-04-02 12:11 UTC, bdavidxyz commented on ui/components/ItemDetail/ItemDetail.js
> +          {kind === "matcha" ? <MatchaDetail job={selectedItem} seeInfo={seeInfo} setSeeInfo={setSeeInfo} /> : ""}
espace

2021-04-02 12:11 UTC, bdavidxyz commented on ui/components/ItemDetail/Job.js
>      let lT = job.place;
jobPlace plutôt ? que signifie lT ?

2021-04-02 12:11 UTC, bdavidxyz commented on ui/utils/mapTools.js
> +  if (lists.matchas) sortedList = sortedList.length ? sortedList.concat(lists.matchas) : lists.matchas;
ajouter des { }

2021-04-02 12:11 UTC, bdavidxyz commented on ui/utils/tools.js
>    if (realItem.ideaType === "peJob") id = `peJob${realItem.job.id}`;
ajouter des { }

2021-04-05 08:28 UTC, alanlr commented on ui/utils/tools.js
>    if (realItem.ideaType === "peJob") id = `peJob${realItem.job.id}`;
-> switch case au passage

2021-04-05 09:21 UTC, alanlr commented on ui/components/ItemDetail/Job.js
>      let lT = job.place;
devait y avoir un autre nom qui collait aux initiales

2021-04-05 09:23 UTC, alanlr commented on ui/components/ItemDetail/ItemDetail.js
> +          {kind === "matcha" ? <MatchaDetail job={selectedItem} seeInfo={seeInfo} setSeeInfo={setSeeInfo} /> : ""}
pas compris :)

2021-04-07 17:14 UTC, merged