311 Bouton de recherche sur carte
mission-apprentissage/labonnealternance-old pull request #236
Opened 2021-04-15 14:46 UTC by alanlr

2021-04-15 15:12 UTC, bdavidxyz requested changes

2021-04-15 15:12 UTC, bdavidxyz commented on ui/components/Map/Map.js
> +import { setSelectedItem } from "store/actions";
+1 pour le chemin absolu !

2021-04-15 15:12 UTC, bdavidxyz commented on ui/components/Map/Map.js
> +    console.log("aaa ", mapPosition, formValues, shouldHandleMapSearch);
à supprimer ?

2021-04-15 15:12 UTC, bdavidxyz commented on ui/components/SearchForTrainingsAndJobs/SearchForTrainingsAndJobs.js
> +  const handleSearchSubmit = async (values,misc) => {
espace manquant

2021-04-16 07:03 UTC, alanlr commented on ui/components/Map/Map.js
> +    console.log("aaa ", mapPosition, formValues, shouldHandleMapSearch);
ofc ;-)

2021-04-16 09:30 UTC, merged