[715] catalog
mission-apprentissage/labonnealternance-old pull request #341
Opened 2021-07-02 12:30 UTC by bdavidxyz

2021-07-08 13:38 UTC, bdavidxyz commented on ui/src/tests/buildLinkForTownAndJob.test.js
> +import { buildLinkForTownAndJob } from '../../utils/buildLinkForTownAndJob'
Note : pas possible de mettre des import absolus dans les tests

2021-07-08 16:21 UTC, alanlr requested changes

2021-07-08 16:21 UTC, alanlr commented on ui/config/metiers.txt
> +Elevage d'animaux de ferme  [A1301,A1403,A1407,A1408,A1416,A1407,A1407,A1409,A1416,A1410,A1411,A1411,A1410,A1411,A1301,A1403,A1409,A1416,A1409,A1409,A1301,A1403,A1409,A1301,A1409,A1409,A1301,A1403]
faudrait alléger en faisant une factorisation des doublons de codes romes

2021-07-08 17:02 UTC, bdavidxyz commented on ui/config/metiers.txt
> +Elevage d'animaux de ferme  [A1301,A1403,A1407,A1408,A1416,A1407,A1407,A1409,A1416,A1410,A1411,A1411,A1410,A1411,A1301,A1403,A1409,A1416,A1409,A1409,A1301,A1403,A1409,A1301,A1409,A1409,A1301,A1403]
oui c'est fait dans le code, mais ça serait aussi bien au niveau du fichier

2021-07-09 10:04 UTC, bdavidxyz commented on ui/next.config.js
> -          require('./scripts/generate-sitemap');
le sitemap sera désormais généré par next-sitemap

2021-07-22 14:39 UTC, merged