Memoization pour régler les appels redondants
mission-apprentissage/labonnealternance-old pull request #365
Opened 2021-08-19 10:07 UTC by alanlr

2021-08-19 12:01 UTC, bdavidxyz requested changes

2021-08-19 12:01 UTC, bdavidxyz commented on ui/utils/memoize.js
> +      console.log("pas memo");
console.log à enlever ?

2021-08-19 12:01 UTC, bdavidxyz commented on ui/utils/memoize.js
> +const memoize = (func) => {
il y a déjà la fonction _.memoize de lodash. A utiliser pour éviter un nouveau test unitaire ;);)

2021-08-19 13:11 UTC, alanlr commented on ui/utils/memoize.js
> +      console.log("pas memo");
Done

2021-08-19 13:12 UTC, alanlr commented on ui/utils/memoize.js
> +const memoize = (func) => {
Commentaire ajouté pour dire pourquoi pas lodash

2021-08-19 15:09 UTC, bdavidxyz approved these changes

2021-08-20 07:52 UTC, bdavidxyz approved these changes
c'est bon pour moi. Juste essayer de mettre des imports absolu au lieu de relatif quand c'est possible.

2021-08-20 08:29 UTC, merged