Internalisation ES catalogue
mission-apprentissage/labonnealternance-old pull request #380
Opened 2021-09-03 09:11 UTC by alanlr

2021-09-03 17:20 UTC, bdavidxyz requested changes

2021-09-03 17:20 UTC, bdavidxyz commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> +  //console.log(msg);
à supprimer

2021-09-03 17:20 UTC, bdavidxyz commented on server/src/service/updateFormations.js
> +/*
bloc de commentaire  à supprimer ?

2021-09-03 17:20 UTC, bdavidxyz commented on server/src/common/components/indexSourceFormations.js
> +    if (_.get(err, "meta.meta.connection.status") === "dead") {
let _.get a moins d'intérêt depuis qu'on peut faire de l'optional chaining https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

meta?.meta?.connection?.status === "dead"

2021-09-03 17:20 UTC, bdavidxyz commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> +    console.log("décompte ? ", formationCount);
faut-il le garder ?

2021-09-03 17:20 UTC, bdavidxyz commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> +      console.log("currentIndex : ", currentIndex);
à garder ?

2021-09-06 09:26 UTC, alanlr commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> +    console.log("décompte ? ", formationCount);
nope, je les tranforme en log messages propres

2021-09-07 12:34 UTC, merged