Feat: diploma level update
mission-apprentissage/labonnealternance-old pull request #437
Opened 2021-10-27 13:50 UTC by kevbarns

Matcha modifie la selection du niveau de formation dans la pop-up d'ajout/modification de l'offre comme suite : 

- Cap, autres formations niveau infrabac
- BP, Bac, autres formations niveau bac
- BTS, DEUST, autres formations niveau bac+2
- Licence, autres formations niveau bac+3
- Master, titre ingénieur, autres formations niveau bac+5

2021-10-29 08:35 UTC, alanlr requested changes

2021-10-29 08:35 UTC, alanlr commented on server/CHANGELOG.md
> +
roo c'est quoi cet affichage tout cassé :) enlève la modif sur ce fichier stp :)

2021-10-29 08:35 UTC, alanlr commented on ui/components/ItemDetail/MatchaDetail.js
> +            <div className="c-detail-diploma d-inline-block">{job.diplomaLevel}</div>
Je bosse mardi, tu me ping pour qu'on en parle ? c'est vu avec Damien ?

2021-11-03 10:41 UTC, kevbarns commented on ui/components/ItemDetail/MatchaDetail.js
> +            <div className="c-detail-diploma d-inline-block">{job.diplomaLevel}</div>
Non pas vu avec Damien, je modifie juste le map pour que le niveau s'affiche correctement, j'ai pas touché au design

2021-11-03 17:27 UTC, kevbarns commented on ui/components/ItemDetail/MatchaDetail.js
> +            <div className="c-detail-diploma d-inline-block">{job.diplomaLevel}</div>
Pour info, le code est en production côté Matcha.

2021-11-09 15:01 UTC, closed without merging