[1072] rencontrer rebased
mission-apprentissage/labonnealternance-old pull request #565
Opened 2022-03-22 12:51 UTC by bdavidxyz

2022-03-22 13:25 UTC, bdavidxyz commented on ui/components/SatisfactionForm/SatisfactionForm.js
> +        // postIntention({ iv, id, intention });
suppression condition complète ?

2022-03-23 16:53 UTC, alanlr requested changes

2022-03-23 16:53 UTC, alanlr commented on server/CHANGELOG.md
> +[1072] Maj Rencontrer le candidat
à passer en 1.18.7, j'ai du faire un hotfix ;-)

2022-03-23 16:53 UTC, alanlr commented on ui/components/SatisfactionForm/SatisfactionForm.js
> +        // postIntention({ iv, id, intention });
oui car on a supprimé les feedback. ca fera du nettoyage

2022-03-23 16:53 UTC, alanlr commented on ui/components/SatisfactionForm/SatisfactionForm.js
> +                    placeholder={`${getValueFromPath("intention") === 'entretien' ? "Nous acceptons votre candidature parce que..." : getValueFromPath("intention") === 'ne_sais_pas' ? "Bonjour, Merci
lors de mon test le placeholder pour le bouton accepter indiquait un refus.
Je pense qu'il y a un souci avec l'imbrication du test ternaire

2022-03-23 16:53 UTC, alanlr commented on ui/components/SatisfactionForm/SatisfactionForm.js
>      if (formType === "avis") {
finalement tout ça qui concerne les avis candidats devrait pouvoir passer à la trappe. A vérifier avec Marion

2022-03-23 16:53 UTC, alanlr commented on ui/components/SatisfactionForm/SatisfactionForm.js
J'ai ça comme erreur react non bloquante qui apparaît dans ma console : Warning: Expected server HTML to contain a matching <div> in <div>.
    in div (at SatisfactionForm.js:38)
    in div (at SatisfactionForm.js:35)
    in div (at SatisfactionForm.js:169)
    in div (at SatisfactionForm.js:168)
    in div (at SatisfactionForm.js:167)
    in div (at SatisfactionForm.js:164)
    in SatisfactionForm (at formulaire-intention.js:12)

2022-03-23 16:53 UTC, alanlr commented on ui/components/SatisfactionForm/SatisfactionForm.js
flûte le post du commentaire à virer qq balises < div > de l'erreur

2022-03-23 18:04 UTC, alanlr commented on server/src/http/routes/sendApplication.js
> +      console.log("req.body for /intentionComment", req.body);
console.log

2022-03-23 18:05 UTC, alanlr commented on server/src/service/applications.js
> +const saveApplicationIntention = async ({ query }) => {
c'est encore appelé ?
les données d'intention ne gagneraient elles pas à être persistées au moment de l'envoi du message au candidat ?

2022-03-25 10:52 UTC, bdavidxyz commented on ui/components/SatisfactionForm/SatisfactionForm.js
C'est corrigé avec les màj normalement

2022-03-31 12:54 UTC, alanlr requested changes
Presque parfait. Le commentaire en cas de refus n'est pas transmis au message.

2022-03-31 13:02 UTC, merged