294 enrichissement info offre mandataire
mission-apprentissage/labonnealternance-old pull request #722
Opened 2022-09-05 15:32 UTC by alanlr

2022-09-05 17:42 UTC, bdavidxyz requested changes

2022-09-05 17:42 UTC, bdavidxyz commented on ui/components/ItemDetail/LocationDetail.js
> +              {new Date(item?.company?.creationDate).getFullYear()}
Mais quelle année est renvoyée si les ?. échouent ?

2022-09-06 07:05 UTC, alanlr commented on ui/components/ItemDetail/LocationDetail.js
> +              {new Date(item?.company?.creationDate).getFullYear()}
je vais mettre une condition d'existence de l'info correcte sur le bloc

2022-09-06 09:10 UTC, bdavidxyz requested changes

2022-09-06 09:10 UTC, bdavidxyz commented on ui/components/ItemDetail/LocationDetail.js
> +                {new Date(item?.company?.creationDate).getFullYear()}
Quelle serait l'année par défaut ?

2022-09-06 09:11 UTC, bdavidxyz requested changes

2022-09-06 09:11 UTC, bdavidxyz commented on ui/components/ItemDetail/LocationDetail.js
> +                {new Date(item?.company?.creationDate).getFullYear()}
ok, mettre item.company.creationDate sans les ?. car la condition a déjà été vérifiée au-dessus

2022-09-06 10:49 UTC, merged